//! `loom-tokens` — typed design tokens.
//!
//! Every constant here is a *unit of trust*: a designer or doctrine
//! reviewer signs off on it once, and every component thereafter
//! consumes it instead of inventing its own value. Adding a token is
//! a doctrine change (review required); using a token is free.
//!
//! Tokens are emitted in two shapes:
//!   * As Tailwind class strings (`spacing(4)` → `"4"` → `"px-4"`)
//!     consumed by `loom-components` to build typed components.
//!   * As JSON (`tokens_json()`) so future non-web generators
//!     (GTK, Jetpack Compose, etc.) can consume the same tokens
//!     without re-implementing them.

#![doc(html_no_source)]

pub mod color;
pub mod radius;
pub mod scale;

pub use color::{Color, ColorRole};
pub use radius::Radius;
pub use scale::{Breakpoint, FontSize, Spacing};

use serde::Serialize;

/// Top-level export of every token as JSON. Stable wire format.
///
/// Future cross-platform generators (GTK theme, Jetpack Compose Theme
/// builder, etc.) consume this to ensure pixel-identical sizing and
/// color across platforms.
#[derive(Debug, Serialize)]
pub struct AllTokens {
    /// Palette by semantic role (`primary`, `slate-900`, etc.) →
    /// value (CSS color string). Light theme.
    pub colors: Vec<ColorRole>,
    /// Same role list, dark-theme resolutions. Cross-platform
    /// generators that target a dark surface (GTK dark, Material
    /// You dynamic) consume this slice.
    pub colors_dark: Vec<ColorRole>,
    /// Spacing scale steps.
    pub spacing: Vec<Spacing>,
    /// Breakpoints in pixels.
    pub breakpoints: Vec<Breakpoint>,
    /// Font sizes.
    pub font_sizes: Vec<FontSize>,
    /// Border radii.
    pub radii: Vec<Radius>,
}

/// Serialize every token to a JSON string. Used by cross-platform
/// theme generators and by the doctrine doc check that the surface
/// is still in sync.
///
/// # Panics
/// Never panics in practice — the token tree is finite and every
/// type derives `Serialize`. The `expect` exists so a future-broken
/// derive would fail the build, not silently corrupt output.
#[must_use]
pub fn tokens_json() -> String {
    let all = AllTokens {
        colors: ColorRole::all().to_vec(),
        colors_dark: ColorRole::dark_all().to_vec(),
        spacing: Spacing::all().to_vec(),
        breakpoints: Breakpoint::all().to_vec(),
        font_sizes: FontSize::all().to_vec(),
        radii: Radius::all().to_vec(),
    };
    serde_json::to_string_pretty(&all).expect("token tree is finite + serde-clean")
}

/// Emit every token as CSS custom properties under `:root` and
/// `:root[data-theme="dark"]`. Drop-in stylesheet for any web
/// surface; the lint expects every raw value to be substituted with
/// `var(--loom-color-*)` / `var(--loom-space-*)` from this output.
#[must_use]
pub fn tokens_css() -> String {
    let mut out = String::new();
    out.push_str("/* Generated by loom-tokens — do NOT edit by hand.\n");
    out.push_str(" * Re-emit via `loom css > path/to/loom-tokens.css`.\n */\n\n");
    out.push_str(":root {\n");
    for role in ColorRole::all() {
        out.push_str(&format!("  --loom-color-{}: {};\n", role.role, role.color.css));
    }
    for sp in Spacing::all() {
        out.push_str(&format!("  --loom-space-{}: {}rem;\n", sp.tailwind(), sp.rem()));
    }
    for bp in Breakpoint::all() {
        out.push_str(&format!("  --loom-break-{}: {}px;\n", bp.tailwind(), bp.px()));
    }
    for fs in FontSize::all() {
        out.push_str(&format!("  --loom-font-{}: {};\n", fs.tailwind(), fs.css_size()));
    }
    for r in Radius::all() {
        out.push_str(&format!("  --loom-radius-{}: {};\n", r.tailwind(), r.css_size()));
    }
    out.push_str("}\n\n");

    out.push_str(":root[data-theme=\"dark\"] {\n");
    for role in ColorRole::dark_all() {
        out.push_str(&format!("  --loom-color-{}: {};\n", role.role, role.color.css));
    }
    out.push_str("}\n");
    out
}

/// Emit every token as a Rust `pub const` block intended for
/// inclusion in an egui-driven app (Atrium etc.). Colors are emitted
/// as `egui::Color32` literals; spacing + radius as `f32` rem
/// multiples that the egui app multiplies by its base font size at
/// startup.
///
/// Output is drop-in: write to `src/loom_tokens.rs`, add
/// `mod loom_tokens;` to `lib.rs`, then reference
/// `loom_tokens::COLOR_PRIMARY` etc.
#[must_use]
pub fn tokens_egui() -> String {
    let mut out = String::new();
    out.push_str("//! Generated by loom-tokens — do NOT edit by hand.\n");
    out.push_str("//! Re-emit via `loom egui > src/loom_tokens.rs`.\n//!\n");
    out.push_str("//! Cross-platform mirror of the loom-tokens CSS output.\n\n");

    out.push_str("/// Light-theme palette as eight-character hex strings.\n");
    out.push_str("pub mod color {\n");
    for role in ColorRole::all() {
        let const_name = role
            .role
            .to_uppercase()
            .replace('-', "_");
        out.push_str(&format!(
            "    /// `{}` — {}\n    pub const {}: &str = \"{}\";\n",
            role.role,
            role.color.tailwind,
            const_name,
            role.color.css,
        ));
    }
    out.push_str("}\n\n");

    out.push_str("/// Dark-theme palette mirror.\n");
    out.push_str("pub mod color_dark {\n");
    for role in ColorRole::dark_all() {
        let const_name = role
            .role
            .to_uppercase()
            .replace('-', "_");
        out.push_str(&format!(
            "    pub const {}: &str = \"{}\";\n",
            const_name, role.color.css,
        ));
    }
    out.push_str("}\n\n");

    out.push_str("/// Spacing scale in rem units. Multiply by base font size at use site.\n");
    out.push_str("pub mod space {\n");
    for sp in Spacing::all() {
        out.push_str(&format!(
            "    /// step {tw} — {rem}rem ({px}px @16)\n    pub const S{tw}_REM: f32 = {rem}_f32;\n    pub const S{tw}_PX: u32 = {px};\n",
            tw = sp.tailwind(),
            rem = sp.rem(),
            px = sp.px(),
        ));
    }
    out.push_str("}\n\n");

    out.push_str("/// Breakpoints in pixel widths.\n");
    out.push_str("pub mod breakpoint {\n");
    for bp in Breakpoint::all() {
        let upper = bp.tailwind().to_uppercase();
        out.push_str(&format!(
            "    pub const {}: u32 = {};\n",
            upper,
            bp.px(),
        ));
    }
    out.push_str("}\n\n");

    out.push_str("/// Border radii (rem units).\n");
    out.push_str("pub mod radius {\n");
    for r in Radius::all() {
        let upper = r.tailwind().to_uppercase();
        out.push_str(&format!(
            "    pub const {}: &str = \"{}\";\n",
            upper,
            r.css_size(),
        ));
    }
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tokens_json_round_trips() {
        let s = tokens_json();
        let v: serde_json::Value = serde_json::from_str(&s).unwrap();
        assert!(v.get("colors").is_some());
        assert!(v.get("colors_dark").is_some());
        assert!(v.get("spacing").is_some());
        assert!(v.get("breakpoints").is_some());
        assert!(v.get("font_sizes").is_some());
        assert!(v.get("radii").is_some());
    }

    /// Reviewer guard: if the token surface ships fewer than the
    /// minimums, something has been deleted that probably should
    /// not have been. Bumps to these numbers are intentional.
    #[test]
    fn token_surface_is_at_least_minimum() {
        assert!(ColorRole::all().len() >= 8, "palette shrunk");
        assert!(Spacing::all().len() >= 10, "spacing scale shrunk");
        assert!(Breakpoint::all().len() >= 4, "breakpoints shrunk");
        assert!(FontSize::all().len() >= 7, "font scale shrunk");
        assert!(Radius::all().len() >= 4, "radius scale shrunk");
    }

    #[test]
    fn css_emitter_covers_every_role_in_root() {
        let css = tokens_css();
        for role in ColorRole::all() {
            let prop = format!("--loom-color-{}:", role.role);
            assert!(css.contains(&prop), "missing {prop} in :root");
        }
        assert!(css.contains(":root[data-theme=\"dark\"]"));
    }

    #[test]
    fn css_emitter_covers_every_spacing_step() {
        let css = tokens_css();
        for sp in Spacing::all() {
            let prop = format!("--loom-space-{}:", sp.tailwind());
            assert!(css.contains(&prop), "missing {prop}");
        }
    }

    #[test]
    fn egui_emitter_emits_color_const_per_role() {
        let rs = tokens_egui();
        for role in ColorRole::all() {
            let const_name = role.role.to_uppercase().replace('-', "_");
            assert!(
                rs.contains(&format!("pub const {const_name}: &str =")),
                "missing const {const_name}",
            );
        }
    }

    #[test]
    fn egui_emitter_compiles_to_valid_rust_lookalike() {
        // Smoke: every line is either a comment, blank, or a known
        // structural token. Detects accidental leakage of strings
        // outside `pub mod` blocks.
        let rs = tokens_egui();
        for line in rs.lines() {
            let s = line.trim_start();
            if s.is_empty() || s.starts_with("//") || s.starts_with("/*") {
                continue;
            }
            let ok = s.starts_with("pub mod")
                || s.starts_with("pub const")
                || s == "}"
                || s.starts_with("pub use")
                || s.starts_with("///")
                || s.starts_with("//!");
            assert!(ok, "unexpected line: {line:?}");
        }
    }
}
