//! `loom journey-from-cms` subcommand — synthesize a Crawler journey
//! JSON from every `cms/*.json` file in a directory tree.
//!
//! Extracted from `main.rs` as part of the bloat-reduction work
//! (Loom issue #3). Body kept byte-for-byte identical to the
//! pre-extraction implementation; visibility on `cmd_journey_from_cms`
//! and `JourneyFromCmsError` was widened to `pub` so the entrypoint
//! can call / pattern-match them through the `mod journey_from_cms;`
//! boundary.
//!
//! Output is deterministic — pages are sorted by source filename so
//! diffs across runs only reflect content changes.

/// `loom journey-from-cms` errors.
#[derive(Debug)]
pub enum JourneyFromCmsError {
    Schema {
        file: std::path::PathBuf,
        error: String,
    },
    Io(std::io::Error),
}

impl From<std::io::Error> for JourneyFromCmsError {
    fn from(e: std::io::Error) -> Self {
        Self::Io(e)
    }
}

pub fn cmd_journey_from_cms(
    cms_dir: &std::path::Path,
    base_url: &str,
    out: &std::path::Path,
    name: &str,
) -> Result<(), JourneyFromCmsError> {
    if !cms_dir.is_dir() {
        return Err(JourneyFromCmsError::Io(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("cms-dir not found: {}", cms_dir.display()),
        )));
    }
    // Collect + parse + sort by path so journey order is
    // deterministic across runs (fs walk order is filesystem-
    // dependent; sorted output makes diffs reviewable).
    let mut json_files = Vec::<std::path::PathBuf>::new();
    walk_cms_json(cms_dir, &mut json_files)?;
    json_files.sort();
    let mut pages = Vec::<(String, String)>::new(); // (path, label)
    for path in &json_files {
        let raw = std::fs::read_to_string(path)?;
        let page: loom_cms_render::CmsPage =
            serde_json::from_str(&raw).map_err(|e| JourneyFromCmsError::Schema {
                file: path.clone(),
                error: e.to_string(),
            })?;
        let label = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("page")
            .to_owned();
        pages.push((page.path, label));
    }
    let journey = build_journey_json(name, base_url, &pages);
    let pretty = serde_json::to_string_pretty(&journey)
        .map_err(|e| JourneyFromCmsError::Io(std::io::Error::other(format!("serialize: {e}"))))?;
    if let Some(parent) = out.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(out, format!("{pretty}\n"))?;
    println!("  ok     {} page(s) → {}", pages.len(), out.display());
    Ok(())
}

fn walk_cms_json(
    dir: &std::path::Path,
    out: &mut Vec<std::path::PathBuf>,
) -> Result<(), std::io::Error> {
    crate::walk::walk_paths_by_ext(dir, out, |e| e == "json")
}

/// Build the journey JSON value. Pure function — testable
/// without filesystem I/O.
fn build_journey_json(name: &str, base_url: &str, pages: &[(String, String)]) -> serde_json::Value {
    let trimmed_base = base_url.trim_end_matches('/');
    let mut steps = Vec::<serde_json::Value>::new();
    for (i, (path, label)) in pages.iter().enumerate() {
        // CmsPage.path may be "/" or "/about.html" — concatenate
        // with the trimmed base so we don't end up with double
        // slashes.
        let url = format!("{trimmed_base}{path}");
        steps.push(serde_json::json!({
            "kind": "goto",
            "url": url,
            "timeout": 10000,
            "label": label,
        }));
        steps.push(serde_json::json!({
            "kind": "wait",
            "ms": 1200,
        }));
        steps.push(serde_json::json!({
            "kind": "screenshot",
            "label": format!("{:02}-{label}", i + 1),
        }));
    }
    serde_json::json!({
        "name": name,
        "description": format!("Auto-generated by `loom journey-from-cms` from {} CmsPage document(s). DO NOT HAND-EDIT — re-run the command instead.", pages.len()),
        "baseUrl": format!("{trimmed_base}/"),
        "steps": steps,
    })
}

#[cfg(test)]
mod cmd_journey_from_cms_tests {
    use super::*;

    fn unique(label: &str) -> std::path::PathBuf {
        crate::test_support::unique_tmp("loom-journey", label)
    }

    #[test]
    fn empty_dir_emits_zero_steps() {
        let dir = unique("empty");
        std::fs::create_dir_all(&dir).expect("mkdir");
        let out = dir.join("journey.json");
        cmd_journey_from_cms(&dir, "http://x/", &out, "empty-test").expect("ok");
        let v: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
        assert_eq!(v["name"], "empty-test");
        assert_eq!(v["steps"].as_array().unwrap().len(), 0);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn errs_on_missing_cms_dir() {
        let dir = std::env::temp_dir().join("loom-journey-missing-zzzzz");
        let _ = std::fs::remove_dir_all(&dir);
        let out = std::env::temp_dir().join("loom-journey-out-zzz.json");
        let r = cmd_journey_from_cms(&dir, "http://x/", &out, "n");
        assert!(matches!(r, Err(JourneyFromCmsError::Io(_))));
    }

    #[test]
    fn schema_error_surfaces_file_path() {
        let dir = unique("bad");
        std::fs::create_dir_all(&dir).expect("mkdir");
        std::fs::write(dir.join("bad.json"), "{not valid json").expect("w");
        let out = dir.join("journey.json");
        let r = cmd_journey_from_cms(&dir, "http://x/", &out, "n");
        match r {
            Err(JourneyFromCmsError::Schema { file, .. }) => {
                assert!(file.ends_with("bad.json"));
            }
            other => panic!("expected schema error, got {other:?}"),
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn build_journey_emits_three_steps_per_page() {
        let pages = vec![
            ("/".to_owned(), "index".to_owned()),
            ("/about.html".to_owned(), "about".to_owned()),
        ];
        let v = build_journey_json("test", "http://x/", &pages);
        let steps = v["steps"].as_array().unwrap();
        assert_eq!(steps.len(), 6); // 3 per page × 2 pages
        // First triple is the index page.
        assert_eq!(steps[0]["url"], "http://x/");
        assert_eq!(steps[0]["kind"], "goto");
        assert_eq!(steps[1]["kind"], "wait");
        assert_eq!(steps[2]["kind"], "screenshot");
        assert_eq!(steps[2]["label"], "01-index");
        // Second triple is about.
        assert_eq!(steps[3]["url"], "http://x/about.html");
        assert_eq!(steps[5]["label"], "02-about");
    }

    #[test]
    fn base_url_trailing_slash_normalized() {
        let pages = vec![("/x".to_owned(), "x".to_owned())];
        let v = build_journey_json("t", "http://x/", &pages);
        assert_eq!(v["steps"][0]["url"], "http://x/x");
        let v2 = build_journey_json("t", "http://x", &pages);
        assert_eq!(v2["steps"][0]["url"], "http://x/x");
        // baseUrl in the output gets a trailing slash either way.
        assert_eq!(v["baseUrl"], "http://x/");
        assert_eq!(v2["baseUrl"], "http://x/");
    }

    #[test]
    fn output_is_deterministic_sorted_by_filename() {
        let dir = unique("sorted");
        std::fs::create_dir_all(&dir).expect("mkdir");
        // Write in non-alphabetical order to verify sort.
        let make = |fname: &str, path: &str| {
            std::fs::write(
                dir.join(fname),
                format!(r#"{{"title":"x","description":"x","path":"{path}","sections":[]}}"#),
            )
            .expect("w");
        };
        make("zeta.json", "/zeta");
        make("alpha.json", "/alpha");
        make("middle.json", "/middle");
        let out = dir.join("journey.json");
        cmd_journey_from_cms(&dir, "http://x/", &out, "n").expect("ok");
        let v: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&out).unwrap()).unwrap();
        let steps = v["steps"].as_array().unwrap();
        // Step labels are <NN>-<filename-stem>, sorted alphabetically.
        // First page = alpha, second = middle, third = zeta.
        assert_eq!(steps[0]["label"], "alpha");
        assert_eq!(steps[3]["label"], "middle");
        assert_eq!(steps[6]["label"], "zeta");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
