//! `loom new` subcommand — scaffold a placeholder Maud view module.
//!
//! Extracted from `main.rs` as part of the bloat-reduction work
//! (Loom issue #3). Each subcommand should live in its own
//! module so the entrypoint stays small and the command surface
//! is greppable.

use anyhow::Result;

/// Scaffold a new Maud view module at `<root>/src/views/<name>.rs`.
///
/// Refuses to overwrite. Validates `name` is kebab-case ASCII.
/// `template` selects the body — `landing` / `legal` / `article`.
pub fn cmd_new(name: &str, root: &std::path::Path, template: &str) -> Result<()> {
    if !name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
    {
        anyhow::bail!("name must be lowercase ASCII + dashes (got {name:?})");
    }
    let module_name = name.replace('-', "_");
    let target = root.join("src/views").join(format!("{module_name}.rs"));
    if target.exists() {
        anyhow::bail!("refuse to overwrite existing {}", target.display());
    }
    let template_body = match template {
        "landing" => template_landing(name, &module_name),
        "legal" => template_legal(name, &module_name),
        "article" => template_article(name, &module_name),
        other => anyhow::bail!("unknown template {other:?}; expected landing | legal | article"),
    };
    std::fs::write(&target, template_body)
        .map_err(|e| anyhow::anyhow!("write {}: {e}", target.display()))?;
    println!("loom new: scaffolded {}", target.display());
    println!();
    println!("Next steps (manual — these are per-crate wiring decisions):");
    println!("  1. Add `pub mod {module_name};` to src/views.rs");
    println!("  2. Add a handler in src/handlers.rs that calls views::{module_name}::render()");
    println!("  3. Add `.route(\"/{name}\", get(handlers::{module_name}))` in main.rs");
    println!("  4. Add the route to SITEMAP_ROUTES if it should be indexed");
    println!(
        "  5. Add `snap_route!({module_name}, \"/{name}\")` if the crate uses insta snapshots"
    );
    Ok(())
}

fn template_landing(name: &str, _module: &str) -> String {
    format!(
        r#"//! `/{name}` — placeholder generated by `loom new {name} --template landing`.

use maud::{{Markup, html}};

use crate::views::layout::page;

#[must_use]
pub fn render() -> Markup {{
    let body = html! {{
        section class="pt-32 pb-16 md:pt-44 md:pb-20 bg-slate-50" {{
            div class="container mx-auto px-4 md:px-6 max-w-4xl" {{
                h1 class="font-display text-4xl md:text-5xl lg:text-6xl font-bold text-slate-900 leading-[1.1] mb-4" {{
                    "{name} headline goes here"
                }}
                p class="text-lg text-slate-600 max-w-2xl leading-relaxed" {{
                    "Subhead. Replace with real content. Default copy lives here so the snapshot test ratchets up to real wording."
                }}
            }}
        }}
    }};
    page("{name} — PlausiDen", "/{name}", body)
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn renders_nonempty() {{
        assert!(render().into_string().len() > 1_000);
    }}
}}
"#
    )
}

fn template_legal(name: &str, _module: &str) -> String {
    format!(
        r#"//! `/{name}` — legal placeholder generated by `loom new {name} --template legal`.

use maud::{{Markup, html}};

use crate::views::layout::page;

#[must_use]
pub fn render() -> Markup {{
    let body = html! {{
        section class="pt-32 pb-16 md:pt-48 md:pb-20 bg-slate-50" {{
            div class="container mx-auto px-4 md:px-6 max-w-3xl" {{
                span class="inline-block px-4 py-1.5 rounded-full bg-primary/10 text-primary font-semibold text-sm mb-6 border border-primary/20" {{
                    "Legal"
                }}
                h1 class="font-display text-4xl md:text-5xl font-bold text-slate-900 leading-[1.1] mb-4" {{
                    "{name}"
                }}
            }}
        }}
        section class="py-16 bg-white" {{
            div class="container mx-auto px-4 md:px-6 max-w-3xl" {{
                div class="rounded-xl border border-amber-200 bg-amber-50 p-6 mb-10" {{
                    p class="text-sm text-amber-900 font-medium mb-2" {{ "Placeholder — under legal review" }}
                    p class="text-sm text-amber-800 leading-relaxed" {{
                        "Replace with the counsel-reviewed text. Until then, this banner is operative."
                    }}
                }}
            }}
        }}
    }};
    page("{name} — PlausiDen", "/{name}", body)
}}
"#
    )
}

fn template_article(name: &str, _module: &str) -> String {
    format!(
        r#"//! `/{name}` — article placeholder generated by `loom new {name} --template article`.

use maud::{{Markup, html}};

use crate::views::layout::page;

#[must_use]
pub fn render() -> Markup {{
    let body = html! {{
        article class="prose prose-slate mx-auto max-w-3xl px-4 md:px-6 pt-32 pb-16" {{
            p class="text-sm text-slate-500 mb-2" {{ "Field note · YYYY-MM-DD · X min read" }}
            h1 class="font-display text-3xl md:text-4xl font-bold text-slate-900 mb-6" {{
                "{name} title goes here"
            }}
            p class="text-lg text-slate-600 leading-relaxed mb-8" {{
                "Lede paragraph. Replace with real content."
            }}
            h2 class="font-display text-2xl md:text-3xl font-bold text-slate-900 mt-12 mb-4" {{
                "First section heading"
            }}
            p class="mb-6" {{ "Body paragraph." }}
        }}
    }};
    page("{name} — PlausiDen", "/{name}", body)
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_landing_contains_name() {
        let s = template_landing("about", "about");
        assert!(s.contains("about headline goes here"));
        assert!(s.contains("page(\"about — PlausiDen\""));
    }

    #[test]
    fn template_legal_contains_legal_banner() {
        let s = template_legal("privacy", "privacy");
        assert!(s.contains("\"Legal\""));
        assert!(s.contains("Placeholder — under legal review"));
    }

    #[test]
    fn template_article_contains_field_note_meta() {
        let s = template_article("dispatch", "dispatch");
        assert!(s.contains("Field note · YYYY-MM-DD"));
        assert!(s.contains("dispatch title goes here"));
    }
}
